---
- set_fact:
    shell: '{{ item.shell | default(user_shell) }}'
    unix_groups: '{{ item.groups | default(user_groups) }}'
    passwordless_sudo: >
      '{{ item.passwordless_sudo | default(user_passwordless_sudo) }}'

- name: Install the users preferred shell
  apt:
    name: '{{ shell | basename }}'

- name: Create user groups
  group:
    name: '{{ item }}'
    state: present
  loop: '{{ unix_groups }}'

- name: Create user
  become: true
  user:
    name: '{{ item.name }}'
    shell: '{{ shell }}'
    groups: '{{ unix_groups }}'

- name: Set passwordless sudo for user
  when: '{{ passwordless_sudo }}'
  become: true
  lineinfile:
    path: /etc/sudoers
    line: '{{ item.name }} ALL=(ALL) NOPASSWD:ALL'

- name: Add public ssh key
  become: true
  authorized_key:
    user: '{{ item.name }}'
    key: '{{ item.ssh_public_key }}'
