---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-role-users
      include_role:
        name: ansible-role-users
      vars:
        users:
          - name: dani
            ssh_public_key: ssh-rsa AAAA
